// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB96tUEW4YPoc7X-qNUCXMPhJCEGHRJR9w',
    appId: '1:289974993415:web:6976dcaf790fe0ead9e0a2',
    messagingSenderId: '289974993415',
    projectId: 'tubing-calculator',
    authDomain: 'tubing-calculator.firebaseapp.com',
    storageBucket: 'tubing-calculator.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVYtwiAByafUd1JbxcQYIgA-N7dWeIm8U',
    appId: '1:289974993415:android:3ed9f1e59ff92663d9e0a2',
    messagingSenderId: '289974993415',
    projectId: 'tubing-calculator',
    storageBucket: 'tubing-calculator.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZUqLOwuBq_I-iKIQTaVU8UbtzqYmXoZc',
    appId: '1:289974993415:ios:58f49e5ab65130efd9e0a2',
    messagingSenderId: '289974993415',
    projectId: 'tubing-calculator',
    storageBucket: 'tubing-calculator.firebasestorage.app',
    iosBundleId: 'com.example.tubingCalculator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZUqLOwuBq_I-iKIQTaVU8UbtzqYmXoZc',
    appId: '1:289974993415:ios:58f49e5ab65130efd9e0a2',
    messagingSenderId: '289974993415',
    projectId: 'tubing-calculator',
    storageBucket: 'tubing-calculator.firebasestorage.app',
    iosBundleId: 'com.example.tubingCalculator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB96tUEW4YPoc7X-qNUCXMPhJCEGHRJR9w',
    appId: '1:289974993415:web:c8025b73030df1bdd9e0a2',
    messagingSenderId: '289974993415',
    projectId: 'tubing-calculator',
    authDomain: 'tubing-calculator.firebaseapp.com',
    storageBucket: 'tubing-calculator.firebasestorage.app',
  );
}
