// 장비 사용법 탭: 튜브 벤더(수동·전동·NC), 전선관 벤더(수동·유압·시카고),
// 실측 캘리브레이션, 톱·절단기, GD402 가스 밀도계 보정, REMS 아미고 2·타이거 SR, 안전.
import 'package:flutter/material.dart';
import 'package:lucide_icons/lucide_icons.dart';

import '../../equipment/equipment_manual.dart';
import 'gd402_manual_page.dart';
import 'reference_widgets.dart';

class RefMachineTab extends StatelessWidget {
  const RefMachineTab({super.key});

  Widget _openManualButton(BuildContext context) {
    return SizedBox(
      width: double.infinity,
      child: OutlinedButton.icon(
        onPressed: () => Navigator.push(
          context,
          MaterialPageRoute(builder: (_) => const Gd402ManualPage()),
        ),
        icon: const Icon(LucideIcons.bookOpen, size: 18),
        label: const Text(
          "전체 매뉴얼 보기(설치·배선·보정 세 가지·경보표 전부)",
          style: TextStyle(fontWeight: FontWeight.w700),
        ),
        style: OutlinedButton.styleFrom(
          foregroundColor: Colors.indigo,
          side: const BorderSide(color: Colors.indigo),
          padding: const EdgeInsets.symmetric(vertical: 12),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(10),
          ),
        ),
      ),
    );
  }

  /// 제조사 설명서(원본 PDF)를 붙여 두고 여는 단추. 장비 대장과 같은 설명서를 쓴다.
  Widget _vendorManualButton(BuildContext context, {required String key, required String title}) {
    return SizedBox(
      width: double.infinity,
      child: OutlinedButton.icon(
        key: Key('vendor_manual_$key'),
        onPressed: () => openEquipManual(context, key: key, title: title),
        icon: const Icon(LucideIcons.bookOpen, size: 18),
        label: const Text("제조사 설명서 (원본 PDF)", style: TextStyle(fontWeight: FontWeight.w700)),
        style: OutlinedButton.styleFrom(
          foregroundColor: Colors.red.shade700,
          side: BorderSide(color: Colors.red.shade700),
          padding: const EdgeInsets.symmetric(vertical: 12),
          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return ListView(
      padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 16),
      children: [
        refIntroBadge(
          "장비마다 쓰는 순서와 함께 주의 사항·정비(점검)·고장 났을 때·쓴 뒤 정리를 적었습니다. 제원(테이크업·게인·반경)은 장비마다 달라서, 처음 쓰는 장비는 '실측 캘리브레이션'을 한 번 하고 설정에 넣어 두십시오.",
        ),
        const SizedBox(height: 16),

        // ── 튜브 ──
        refCard(
          title: "1. 튜브 수동 벤더 (Swagelok·Ridgid형)",
          subtitle: "튜브 벤딩의 기본. 슈(다이)·롤러·핸들",
          icon: Icons.handyman_outlined,
          iconColor: Colors.brown,
          children: [
            refSectionTitle("쓰는 순서"),
            refButtonGuide(
              btnName: "0 마크",
              purpose: "모든 벤딩의 시작 기준",
              action:
                  "튜브에 그은 마킹선을 슈의 '0' 눈금에 정확히 맞춘다. 계산기 마킹은 이 자리를 기준으로 찍혀 있다.",
            ),
            refGap(),
            refButtonGuide(
              btnName: "R 마크 / L 마크",
              purpose: "어느 쪽에서 치수를 쟀는지",
              action:
                  "튜브 끝에서 벤드까지 잰 치수(정방향)면 R, 시작점부터 잰 치수면 L에 마킹선을 맞춘다. 계산기 '마킹 위치(줄자 0점 기준)'는 R 방식이다.",
            ),
            refGap(),
            refButtonGuide(
              btnName: "롤러 핀·클램프",
              purpose: "튜브가 슈에서 뜨지 않게",
              action:
                  "튜브를 넣고 롤러(링크)를 내린 뒤 핀을 끝까지 밀어 넣는다. 핀이 덜 들어가면 각도가 모자라고 관이 눌린다.",
            ),
            refGap(),
            refButtonGuide(
              btnName: "각도 눈금",
              purpose: "목표 각도 + 스프링백",
              action:
                  "롤러의 0 눈금이 슈의 목표 각도(예 90)를 지나 스프링백만큼(2~3°) 더 가도록 지그시 한 번에 당긴다. 멈췄다 다시 당기면 자국이 남는다.",
            ),
            refGap(),
            refSectionTitle("주의 사항"),
            refDataRow("끼임", "롤러와 슈 사이에 손가락을 두지 않는다. 당길 때 핸들 끝을 잡는다."),
            refGap(),
            refDataRow("규격", "관 바깥지름에 맞는 벤더만 쓴다. 3/8\" 벤더에 10 mm 관처럼 비슷한 크기를 넣으면 관이 눌린다."),
            refGap(),
            refDataRow("남는 길이", "클램프가 물 만큼 곧은 길이가 남아야 한다. 짧으면 관이 빠지며 손을 친다."),
            refGap(),
            refDataRow("힘", "핸들에 파이프를 끼워 늘려 당기지 않는다. 벤더가 휘면 각도가 영영 틀어진다."),
            refGap(),
            refSectionTitle("정비 (점검)"),
            refDataRow("쓸 때마다", "슈 홈·롤러 홈의 쇳가루·모래를 닦는다. 홈에 흠이 있으면 관에 자국이 그대로 찍힌다."),
            refGap(),
            refDataRow("피벗·핀", "피벗 유격과 롤러 핀이 휘지 않았는지 본다. 피벗에만 기름 한 방울, 홈에는 바르지 않는다."),
            refGap(),
            refDataRow("핸들", "핸들 볼트가 풀리지 않았는지 조여 본다."),
            refGap(),
            refSectionTitle("고장 났을 때"),
            refDataRow("관이 납작하다·주름", "규격이 안 맞는 슈, 롤러 핀 덜 들어감, 관 두께가 너무 얇음."),
            refGap(),
            refDataRow("각도가 모자라다", "스프링백만큼 더 당기지 않았다. 롤러 핀이 끝까지 안 들어갔다."),
            refGap(),
            refDataRow("관에 긁힌 자국", "홈에 이물이 있거나 홈이 상했다. 닦고, 흠이면 슈를 바꾼다."),
            refGap(),
            refDataRow("길이가 어긋난다", "0 마크·R·L 마크를 헷갈렸거나 설정의 게인이 이 벤더 값이 아니다(실측 캘리브레이션)."),
            refGap(),
            refDataRow("핸들이 뻑뻑하다", "피벗에 이물·녹. 닦고 기름 한 방울."),
            refGap(),
            refSectionTitle("쓴 뒤 정리"),
            refStep(1, "홈의 쇳가루·먼지를 닦는다."),
            refStep(2, "롤러·핀을 제자리에 끼워 둔다(따로 굴러다니면 잃어버린다)."),
            refStep(3, "규격별로 케이스에 넣는다. 떨어뜨리면 슈가 틀어져 각도가 바뀐다."),
          ],
        ),
        const SizedBox(height: 16),

        refCard(
          title: "2. Swagelok 전동 벤더 (MS-BTB)",
          subtitle: "펜던트로 각도를 넣는 단일 벤딩용",
          icon: Icons.precision_manufacturing,
          iconColor: Colors.orange.shade800,
          children: [
            refSectionTitle("쓰는 순서"),
            refButtonGuide(
              btnName: "[ANGLE] / [SPRINGBACK]",
              purpose: "벤딩 각도와 스프링백 보상",
              action: "목표 각도(예 90)와 스프링백(예 2.5)을 넣는다. 설정에 넣어 둔 스프링백 값과 같게.",
            ),
            refGap(),
            refButtonGuide(
              btnName: "토글 클램프",
              purpose: "튜브 고정",
              action: "마킹선을 0점에 맞추고 클램프 레버를 끝까지 민다. 덜 물리면 튜브가 밀려 마킹이 어긋난다.",
            ),
            refGap(),
            refButtonGuide(
              btnName: "[BEND] 스위치",
              purpose: "벤딩 실행",
              action:
                  "끝날 때까지 꾹 누른다. 손을 떼면 비상 정지. 끝나면 [RETURN]으로 암을 되돌린 뒤 클램프를 푼다.",
            ),
            refGap(),
            refSectionTitle("주의 사항"),
            refDataRow("비상 정지", "켜기 전에 비상 정지 자리를 먼저 본다. [BEND]에서 손을 떼면 멈춘다."),
            refGap(),
            refDataRow("도는 반경", "암이 도는 반경과 관 뒤쪽 끝이 휘두르는 자리에 사람·자재가 없게 한다."),
            refGap(),
            refDataRow("클램프", "끝까지 물렸는지 본다. 덜 물리면 관이 밀려 마킹이 어긋나고 관이 튄다."),
            refGap(),
            refDataRow("전원", "접지된 콘센트. 펜던트 선을 밟거나 꺾지 않는다."),
            refGap(),
            refSectionTitle("정비 (점검)"),
            refDataRow("쓸 때마다", "다이·롤러·클램프 블록 홈을 닦는다. 클램프 블록이 닳으면 관이 미끄러진다."),
            refGap(),
            refDataRow("각도 확인", "가끔 시험 벤딩을 해서 각도기로 90°를 잰다. 틀리면 스프링백 값을 고친다."),
            refGap(),
            refDataRow("선", "펜던트·전원선 피복과 플러그를 본다."),
            refGap(),
            refDataRow("속 부품", "모터·기어 소리가 달라지면 직접 열지 말고 서비스센터."),
            refGap(),
            refSectionTitle("고장 났을 때"),
            refDataRow("안 움직인다", "전원 → 비상 정지가 풀렸는지 → 암이 원위치인지([RETURN] 먼저) → 서비스센터."),
            refGap(),
            refDataRow("각도가 매번 다르다", "클램프 덜 물림, 스프링백 값, 관 재질·두께가 달라짐."),
            refGap(),
            refDataRow("관이 미끄러진다", "클램프 블록이 닳았거나 기름이 묻었다. 닦고, 닳았으면 바꾼다."),
            refGap(),
            refDataRow("이상한 소리·냄새", "바로 멈추고 플러그를 뽑는다. 장비 대장에서 '수리·점검 중'으로."),
            refGap(),
            refSectionTitle("쓴 뒤 정리"),
            refStep(1, "[RETURN]으로 암을 원위치에 둔다."),
            refStep(2, "전원을 끄고 플러그를 뽑는다."),
            refStep(3, "다이를 빼서 닦아 규격별로 보관한다."),
            refStep(4, "펜던트 선을 느슨히 감고 덮개를 씌운다."),
          ],
        ),
        const SizedBox(height: 16),

        refCard(
          title: "3. TRACTO-TECHNIK TB20D (NC 벤더)",
          subtitle: "제어반에 순서를 넣고 풋 페달로 연속 작업",
          icon: LucideIcons.monitorSmartphone,
          iconColor: Colors.indigo,
          children: [
            refSectionTitle("쓰는 순서"),
            refButtonGuide(
              btnName: "1. 원점 복귀 [HOME]/[REF]",
              purpose: "영점 잡기 (제일 중요)",
              action:
                  "전원을 켜면 먼저 [HOME] 또는 [REF]를 눌러 암을 0°로. 건너뛰면 엉뚱한 각으로 꺾여 충돌한다.",
            ),
            refGap(),
            refButtonGuide(
              btnName: "2. 프로그램 [PROG]",
              purpose: "벤딩 순서 저장",
              action:
                  "새 번호를 열고 Step 1부터 각도와 스프링백(Korr)을 순서대로 ENTER. 계산기 '마킹 가이드'의 벤드 순서와 같게 넣는다.",
            ),
            refGap(),
            refButtonGuide(
              btnName: "3. 스토퍼·클램프",
              purpose: "튜브 자리 잡기",
              action: "튜브를 넣고 뒤쪽 수동 스토퍼(길이·회전)에 밀착. [CLAMP] 또는 페달 1단으로 물린다.",
            ),
            refGap(),
            refButtonGuide(
              btnName: "4. [AUTO] + 풋 페달",
              purpose: "저장한 순서대로 실행",
              action:
                  "페달을 끝까지 밟으면 Step 1 각도까지 꺾고 멈춘다. 풀고 다음 마킹까지 밀어 넣고 다시 밟으면 Step 2.",
            ),
            const SizedBox(height: 12),
            refWarnBox(
              "화면의 현재 Step 번호를 늘 확인. 순서가 꼬이면 90° 자리에 45°가 들어가 튜브를 버린다.",
            ),
            const SizedBox(height: 12),
            refSectionTitle("TB20D 권장 금형·연신율 (SUS)"),
            refTable(
              headers: const ["규격", "표준 금형 CLR", "권장 연신율"],
              rows: const [
                ['1/4" (6.35)', "R15.0", "7.0~8.0"],
                ['3/8" (9.52)', "R22.5", "11.0~12.5"],
                ['1/2" (12.7)', "R35.0", "18.0~20.0"],
                ['3/4" (19.05)', "R50.0", "26.0~28.0"],
              ],
              footer:
                  "※ 금형 CLR이 수동 벤더(R14.3/23.8/38.1)와 다릅니다. 설정의 반경을 이 장비 값으로 바꾸고 마킹하십시오.",
            ),
            refGap(),
            refSectionTitle("주의 사항"),
            refDataRow("원점", "켜면 원점 복귀부터. 건너뛰면 엉뚱한 각으로 꺾여 충돌한다."),
            refGap(),
            refDataRow("휘두르는 관", "긴 관은 꺾일 때 뒤쪽이 크게 돈다. 그 반경 안에서 사람을 비킨다."),
            refGap(),
            refDataRow("페달", "한 번에 끝까지 밟고, 끝나면 발을 뗀다. 두 번 밟으면 다음 Step이 바로 돈다."),
            refGap(),
            refDataRow("금형 바꾸기", "전원을 끄고 바꾼다. 비상 정지 자리를 늘 확인한다."),
            refGap(),
            refSectionTitle("정비 (점검)"),
            refDataRow("쓸 때마다", "금형·클램프 다이 홈을 닦는다."),
            refGap(),
            refDataRow("각도·길이 확인", "가끔 시험 벤딩으로 각도와 길이를 잰다. 틀리면 Korr(스프링백)·연신율 값을 고친다."),
            refGap(),
            refDataRow("선·페달", "페달 선과 전원선 피복을 본다."),
            refGap(),
            refDataRow("화면 경보", "경보가 뜨면 코드를 적어 둔다. 같은 경보가 되풀이되면 서비스센터."),
            refGap(),
            refSectionTitle("고장 났을 때"),
            refDataRow("원점 복귀가 안 된다", "걸린 것이 없는지 보고 다시. 그래도 안 되면 센서 문제, 서비스센터."),
            refGap(),
            refDataRow("각도가 틀리다", "Korr 값, 관 재질이 바뀜, 클램프 덜 물림."),
            refGap(),
            refDataRow("길이가 틀리다", "연신율 값이 금형·관과 안 맞다(아래 표)."),
            refGap(),
            refDataRow("화면에 경보", "코드를 적고 제조사 설명서의 경보표를 본다. 모르면 서비스센터."),
            refGap(),
            refDataRow("관이 미끄러진다", "클램프 다이가 닳았거나 기름. 닦거나 바꾼다."),
            refGap(),
            refSectionTitle("쓴 뒤 정리"),
            refStep(1, "원점 복귀를 한 뒤 전원을 끈다."),
            refStep(2, "금형을 빼서 닦아 보관한다."),
            refStep(3, "쓴 프로그램 번호를 적어 둔다(앱 일지나 메모)."),
            refStep(4, "바닥의 잘라낸 관·쇳가루를 치운다."),
          ],
        ),
        const SizedBox(height: 16),

        // ── 전선관 ──
        refCard(
          title: "4. 전선관 수동 벤더 (Greenlee·Ideal형)",
          subtitle: "발로 밟아 꺾는 히키 벤더. 슈에 화살표·별·림 표시가 있다",
          icon: LucideIcons.wrench,
          iconColor: Colors.brown,
          children: [
            refSectionTitle("쓰는 순서"),
            refButtonGuide(
              btnName: "화살표 (Arrow)",
              purpose: "90°·오프셋 마킹을 맞추는 표시",
              action: "관에 찍은 마킹선을 화살표에 맞춘다. 계산기 마킹은 테이크업을 이미 뺀 '화살표 자리'다.",
            ),
            refGap(),
            refButtonGuide(
              btnName: "별 (Star)",
              purpose: "뒤로 꺾을 때(백투백) 기준",
              action: "두 번째 90°를 관 끝 쪽에서 재서 꺾을 때 마킹선을 별에 맞춘다.",
            ),
            refGap(),
            refButtonGuide(
              btnName: "림 표시 (Rim notch)",
              purpose: "새들 가운데 벤드",
              action: "3벤드 새들의 가운데 마킹(45°)을 림 홈에 맞춘다. 양옆 22.5°는 화살표.",
            ),
            refGap(),
            refButtonGuide(
              btnName: "발판·핸들",
              purpose: "꺾기",
              action:
                  "발판을 밟으며 핸들을 당긴다. 슈 눈금이 목표 각도 + 스프링백(후강 3~5°)까지. 바닥에 관이 뜨면 각이 모자란 것.",
            ),
            refGap(),
            refButtonGuide(
              btnName: "순서 (오프셋)",
              purpose: "두 벤드가 같은 평면에",
              action:
                  "첫 벤드 뒤 관을 뒤집지 말고 슈 안에서 180° 돌려 두 번째 마킹을 화살표에 맞춘다. 관에 그은 세로 선이 슈 가운데와 나란한지 본다(개 다리 방지).",
            ),
            refGap(),
            refSectionTitle("주의 사항"),
            refDataRow("발판", "발판을 확실히 밟는다. 발이 빠지면 관이 튀어 얼굴로 온다."),
            refGap(),
            refDataRow("바닥", "미끄러운 바닥·기울어진 곳에서는 하지 않는다."),
            refGap(),
            refDataRow("핸들", "핸들에 파이프를 끼워 늘리지 않는다. 손잡이가 휜다."),
            refGap(),
            refDataRow("허리", "굵은 관은 무리하지 말고 유압식으로."),
            refGap(),
            refSectionTitle("정비 (점검)"),
            refDataRow("쓸 때마다", "슈 홈의 흙·쇳가루를 턴다. 녹·흠이 있으면 관에 자국이 난다."),
            refGap(),
            refDataRow("표시", "화살표·별·림 표시가 지워졌으면 다시 새긴다."),
            refGap(),
            refDataRow("손잡이", "손잡이 나사가 풀리지 않았는지 본다."),
            refGap(),
            refSectionTitle("고장 났을 때"),
            refDataRow("개 다리(두 벤드가 비틀림)", "두 번째 벤드 때 관을 돌렸다. 관에 그은 세로선을 슈 가운데와 맞춘다."),
            refGap(),
            refDataRow("각도가 모자라다", "스프링백만큼 더 꺾지 않았다."),
            refGap(),
            refDataRow("관이 납작하다", "규격이 안 맞는 슈, EMT용 슈에 후강을 넣었다."),
            refGap(),
            refDataRow("길이가 틀리다", "화살표·별을 헷갈렸거나 테이크업 설정이 이 벤더 값이 아니다."),
            refGap(),
            refSectionTitle("쓴 뒤 정리"),
            refStep(1, "홈의 흙·쇳가루를 턴다."),
            refStep(2, "녹 막이 기름은 바깥에만 얇게(홈에는 바르지 않는다)."),
            refStep(3, "손잡이를 빼서 같이 보관한다. 크기별로."),
          ],
        ),
        const SizedBox(height: 16),

        refCard(
          title: "5. 유압식 벤더 (Greenlee·Current Tools형)",
          subtitle: "슈를 규격에 맞게 갈아 끼우고 램으로 민다",
          icon: Icons.precision_manufacturing,
          iconColor: Colors.indigo,
          children: [
            refSectionTitle("쓰는 순서"),
            refButtonGuide(
              btnName: "슈·받침(다이) 고르기",
              purpose: "규격에 맞는 곡선",
              action:
                  "관 호칭과 같은 슈를 램에 끼우고, 받침 롤러(다이)는 프레임의 그 호칭 구멍에 핀으로 꽂는다. 핀이 끝까지 안 들어가면 절대 밀지 않는다.",
            ),
            refGap(),
            refButtonGuide(
              btnName: "셋백 마크 맞추기",
              purpose: "꺾이는 점 자리",
              action: "계산기 마킹(셋백을 뺀 자리)을 슈 가운데 표시에 맞춘다. 관은 받침 롤러 양쪽에 고르게 걸친다.",
            ),
            refGap(),
            refButtonGuide(
              btnName: "펌프·램",
              purpose: "꺾기",
              action:
                  "펌프 밸브를 잠그고 펌프질(전동은 스위치). 램 눈금이 설정의 '램 이동 거리'(90°)·각도별 환산값까지 나오면 멈춘다. 각도기로 재고 부족하면 조금 더.",
            ),
            refGap(),
            refButtonGuide(
              btnName: "되돌리기",
              purpose: "관 빼기",
              action: "릴리스 밸브를 천천히 열어 램을 넣는다. 갑자기 열면 슈가 튄다. 관을 빼고 다음 마킹.",
            ),
            const SizedBox(height: 12),
            refWarnBox(
              "램이 나갈 때 손·발을 슈와 받침 사이에 두지 않는다. 핀이 반쯤 꽂힌 채 밀면 핀이 총알처럼 튄다.",
            ),
            refGap(),
            refSectionTitle("주의 사항"),
            refDataRow("호스", "꺾이거나 밟힌 호스, 새는 커플러는 쓰지 않는다. 압력 걸린 채 커플러를 빼지 않는다."),
            refGap(),
            refDataRow("압력", "펌프 정격 압력을 넘기지 않는다. 더 안 꺾이면 슈·관 규격부터 본다."),
            refGap(),
            refDataRow("핀", "받침 핀은 끝까지. 반쯤 꽂힌 채 밀면 핀이 튄다."),
            refGap(),
            refDataRow("서는 자리", "램 앞·슈와 받침 사이에 서지 않는다."),
            refGap(),
            refSectionTitle("정비 (점검)"),
            refDataRow("쓸 때마다", "오일 샘(호스·커플러·램 씰)을 본다. 램 표면의 흙·물기를 닦는다."),
            refGap(),
            refDataRow("오일", "펌프 오일량을 본다. 모자라면 설명서의 오일로 채운다."),
            refGap(),
            refDataRow("슈·받침·핀", "홈의 흠, 핀이 휘지 않았는지 본다."),
            refGap(),
            refDataRow("공기 빼기", "램이 출렁이거나 느리면 공기가 찬 것이다. 설명서 순서대로 뺀다."),
            refGap(),
            refSectionTitle("고장 났을 때"),
            refDataRow("램이 안 나간다", "릴리스 밸브가 열려 있다, 오일 부족, 커플러 덜 꽂힘."),
            refGap(),
            refDataRow("램이 저절로 들어간다", "릴리스 밸브를 덜 잠갔다, 씰에서 샌다."),
            refGap(),
            refDataRow("느리다·출렁인다", "오일 부족, 공기가 찼다."),
            refGap(),
            refDataRow("관이 찌그러진다", "슈·받침 규격이 다르거나 받침 구멍을 잘못 골랐다."),
            refGap(),
            refDataRow("기름이 샌다", "쓰지 말고 씰 교체를 맡긴다. 장비 대장에서 '수리·점검 중'으로."),
            refGap(),
            refSectionTitle("쓴 뒤 정리"),
            refStep(1, "릴리스 밸브를 열어 램을 끝까지 넣고 압력을 뺀다."),
            refStep(2, "커플러에 먼지 덮개를 씌운다."),
            refStep(3, "호스는 꺾이지 않게 크게 감는다."),
            refStep(4, "슈·받침·핀을 닦아 규격별로 넣는다. 흘린 오일은 닦는다."),
          ],
        ),
        const SizedBox(height: 16),

        refCard(
          title: "6. 시카고식 벤더 (기어·크랭크)",
          subtitle: "슈를 기어로 돌려 꺾는다. 굵은 후강에 쓴다",
          icon: LucideIcons.cog,
          iconColor: Colors.deepOrange,
          children: [
            refSectionTitle("쓰는 순서"),
            refButtonGuide(
              btnName: "롤러·슈 맞추기",
              purpose: "규격에 맞는 홈",
              action:
                  "관 호칭에 맞는 롤러 규격(설정의 '롤러 규격')과 슈 홈에 관을 넣는다. 훅(고리)이 관을 꽉 눌러야 한다.",
            ),
            refGap(),
            refButtonGuide(
              btnName: "0점·마킹",
              purpose: "시작 자리",
              action: "노치 휠을 0에 두고 마킹선(테이크업 뺀 자리)을 슈 표시에 맞춘다.",
            ),
            refGap(),
            refButtonGuide(
              btnName: "크랭크·노치",
              purpose: "각도만큼 돌리기",
              action:
                  "크랭크를 돌리며 넘어가는 노치 칸을 센다. 칸 수 = 목표 각도 ÷ 노치당 각도(설정값). 스프링백만큼 한두 칸 더.",
            ),
            refGap(),
            refButtonGuide(
              btnName: "되돌리기 레버",
              purpose: "관 빼기",
              action: "래칫을 풀고 크랭크를 되돌린다. 관을 빼기 전에 훅을 먼저 푼다.",
            ),
            refGap(),
            refSectionTitle("주의 사항"),
            refDataRow("반동", "래칫을 풀 때 크랭크가 되돌아 돈다. 손잡이를 잡고 푼다."),
            refGap(),
            refDataRow("기어", "도는 기어·노치 휠에 손가락을 두지 않는다."),
            refGap(),
            refDataRow("고정", "프레임이 넘어지지 않게 바닥에 고정하거나 받친다."),
            refGap(),
            refDataRow("무게", "굵은 후강은 무겁다. 관 끝을 받쳐 줄 사람이나 받침대를 둔다."),
            refGap(),
            refSectionTitle("정비 (점검)"),
            refDataRow("쓸 때마다", "기어·래칫 사이 쇳가루를 턴다."),
            refGap(),
            refDataRow("기름", "기어·축에 설명서의 그리스를 바른다. 홈에는 바르지 않는다."),
            refGap(),
            refDataRow("훅·롤러", "훅이 관을 꽉 누르는지, 롤러 홈이 닳지 않았는지 본다."),
            refGap(),
            refDataRow("노치 표시", "노치 휠 0 표시가 잘 보이는지 본다."),
            refGap(),
            refSectionTitle("고장 났을 때"),
            refDataRow("래칫이 헛돈다", "래칫에 이물이 끼었거나 스프링이 약하다."),
            refGap(),
            refDataRow("각도가 틀리다", "노치당 각도 설정이 이 벤더 값이 아니다(실측 캘리브레이션), 스프링백."),
            refGap(),
            refDataRow("관이 미끄러진다", "훅이 덜 눌렀다."),
            refGap(),
            refDataRow("크랭크가 뻑뻑하다", "그리스가 말랐다."),
            refGap(),
            refSectionTitle("쓴 뒤 정리"),
            refStep(1, "훅을 풀고 크랭크를 0으로 되돌린다."),
            refStep(2, "기어·홈의 쇳가루를 턴다."),
            refStep(3, "크랭크를 빼서 같이 보관하고 덮개를 씌운다."),
          ],
        ),
        const SizedBox(height: 16),

        // ── 실측 ──
        refCard(
          title: "7. 내 장비 실측 캘리브레이션 (한 번만)",
          subtitle: "제원표는 기계마다 달라 못 믿습니다. 한 번 재서 설정에 넣으면 그 뒤로는 자동입니다",
          icon: Icons.straighten_rounded,
          iconColor: Colors.deepPurple,
          children: [
            refSectionTitle("하는 순서"),
            refButtonGuide(
              btnName: "① 테이크업 / 셋백 (수동·시카고·유압 공통)",
              purpose: "첫 벤딩점에서 빼야 할 값",
              action:
                  "곧은 관 끝에서 300~500mm 자리에 선을 긋고, 그 선을 벤더 0점(화살표·별)에 맞춰 90°로 꺾는다.\n"
                  "꺾은 뒤 관 끝에서 바깥면(등)까지 잰다.\n"
                  "테이크업 = 잰 길이 − 처음 그은 선까지의 길이. 전선관 계산기 설정의 '실측 보정' 창에 두 값을 넣으면 앱이 셈해 준다.",
            ),
            refGap(),
            refButtonGuide(
              btnName: "② 게인 (전 기종 공통)",
              purpose: "90°에서 줄어드는 길이",
              action:
                  "관 하나를 정확한 길이(예 500mm)로 잘라 한가운데를 90°로 꺾는다.\n"
                  "꺾인 점(교차점)에서 양쪽 끝까지 잰다(A, B).\n"
                  "게인 = A + B − 500. 튜브 계산기 설정의 게인 칸, 전선관 계산기의 '벤딩 게인' 칸에 넣는다.",
            ),
            refGap(),
            refButtonGuide(
              btnName: "③ 유압식 — 램 이동 거리",
              purpose: "각도별 램 눈금",
              action:
                  "①과 같이 90°로 꺾으면서 램에 붙은 눈금 값을 적는다. 45°도 한 번 더 재 두면 사이 각도를 더 정확히 셈한다.",
            ),
            refGap(),
            refButtonGuide(
              btnName: "④ 시카고식 — 노치당 각도",
              purpose: "기어 한 칸이 몇 도인지",
              action:
                  "0점에서 90°가 될 때까지 넘어간 노치 칸 수를 센다. 노치당 각도 = 90 ÷ 칸 수. 노치 간격은 이웃 노치 사이를 자로 잰다.",
            ),
            refGap(),
            refButtonGuide(
              btnName: "⑤ 스프링백",
              purpose: "더 꺾어야 하는 각",
              action:
                  "90° 눈금까지 꺾고 풀어 각도기로 잰다. 90 − 잰 각 = 스프링백. 설정의 '스프링백 [°]'에 넣는다.",
            ),
            const SizedBox(height: 12),
            refTipBox(
              "잰 값은 튜브 계산기 '설정' 탭(수동/유압식/시카고식 제원 칸), 전선관 계산기 '설정'(제조사·재질·규격별)에 넣습니다. 규격마다 따로 저장되니 한 번만 하면 됩니다.",
            ),
            refGap(),
            refSectionTitle("주의 사항"),
            refDataRow("같은 조건", "같은 장비·같은 슈·같은 관 재질과 두께로 잰다. 하나라도 다르면 값이 다르다."),
            refGap(),
            refDataRow("재는 법", "줄자 0점을 확인하고 관 끝을 직각으로 자른 뒤 잰다. 스프링백은 풀고 나서 잰다."),
            refGap(),
            refDataRow("여러 번", "한 번이 아니라 두세 번 재서 비슷한지 본다."),
            refGap(),
            refSectionTitle("다시 잴 때"),
            refDataRow("슈를 바꿨을 때", "슈·다이를 바꾸거나 새로 샀으면 다시 잰다."),
            refGap(),
            refDataRow("수리 뒤", "장비를 고쳤거나 떨어뜨렸으면 다시 잰다."),
            refGap(),
            refDataRow("차이가 계속 날 때", "벤딩 실측 기록에서 계산과 잰 값 차이가 늘 한쪽으로 나면 다시 잰다."),
            refGap(),
            refSectionTitle("값이 이상할 때"),
            refDataRow("테이크업이 마이너스·너무 크다", "0점(화살표·별)을 헷갈렸거나, 등이 아니라 안쪽 면을 쟀다."),
            refGap(),
            refDataRow("게인이 이상하다", "교차점을 잘못 잡았다. 두 직선을 연장해 만나는 점에서 잰다."),
            refGap(),
            refDataRow("잴 때마다 다르다", "관이 미끄러졌다(클램프), 관 재질이 섞였다."),
            refGap(),
            refSectionTitle("잰 뒤 정리"),
            refStep(1, "잰 값을 계산기 설정에 넣고 저장한다."),
            refStep(2, "장비 관리 대장의 그 장비 메모에 날짜와 값을 적어 둔다."),
            refStep(3, "시험으로 꺾은 관은 잔재로 올리거나 버린다."),
          ],
        ),
        const SizedBox(height: 16),

        // ── 절단 ──
        refCard(
          title: "8. 튜브 커터 · 디버링",
          subtitle: "튜브는 톱이 아니라 커터로 자른다",
          icon: LucideIcons.scissors,
          iconColor: Colors.teal,
          children: [
            refSectionTitle("쓰는 순서"),
            refStep(1, "마킹선에 커터 날을 맞추고 가볍게 조인 뒤 한 바퀴 돌린다."),
            refStep(2, "돌릴 때마다 손잡이를 1/4바퀴씩만 조인다. 한 번에 세게 조이면 관 끝이 안으로 말린다."),
            refStep(
              3,
              "잘린 면의 안팎 버를 디버링 툴로 깎는다. 안쪽 버는 유량을 막고, 바깥 버는 페룰 자리를 긁는다.",
            ),
            refStep(4, "끝면이 관 축과 직각인지 본다. 비스듬하면 피팅 턱에 닿지 않아 샌다."),
            refStep(5, "자르기 전 계산기의 '총 절단 길이'와 마킹지(PDF)를 한 번 더 대조한다."),
            refGap(),
            refSectionTitle("주의 사항"),
            refDataRow("날", "커터 날·디버링 날은 날카롭다. 스테인리스 버에 손이 베인다."),
            refGap(),
            refDataRow("조이기", "한 번에 세게 조이지 않는다. 관 끝이 안으로 말리고 날이 상한다."),
            refGap(),
            refSectionTitle("정비 (점검)"),
            refDataRow("날", "이가 빠진 날은 바꾼다. 여분 날을 같이 둔다."),
            refGap(),
            refDataRow("롤러", "롤러가 부드럽게 도는지 본다."),
            refGap(),
            refDataRow("디버링 툴", "날이 무디면 버가 남는다. 바꾼다."),
            refGap(),
            refSectionTitle("고장 났을 때"),
            refDataRow("관 끝이 안으로 말린다", "너무 세게 조였다. 1/4바퀴씩."),
            refGap(),
            refDataRow("나선으로 돈다(직각이 안 된다)", "처음 바퀴를 세게 조였거나 날·롤러가 닳았다."),
            refGap(),
            refDataRow("버가 크다", "날이 무디다."),
            refGap(),
            refSectionTitle("쓴 뒤 정리"),
            refStep(1, "쇳가루를 턴다."),
            refStep(2, "날을 보호해 공구함에 넣는다. 여분 날과 같이."),
          ],
        ),
        const SizedBox(height: 16),

        refCard(
          title: "9. 고속절단기 · 밴드쏘 · 전선관 나사",
          subtitle: "형강·전선관 절단",
          icon: LucideIcons.zap,
          iconColor: Colors.redAccent,
          children: [
            refSectionTitle("쓰는 순서"),
            refStep(
              1,
              "톱날 두께를 재서 형강 컷팅·튜브 컷팅 화면의 '톱날 손실'에 넣는다(고속절단기 2.5~3mm, 밴드쏘 1.3~1.6mm).",
            ),
            refStep(2, "재단 계획 순서대로 긴 조각부터 자른다. 자재를 바이스에 꽉 물린다."),
            refStep(3, "절단기는 날을 자재에 댄 채 시동하지 않는다. 회전이 다 오른 뒤 천천히 내린다."),
            refStep(4, "밴드쏘는 자재를 밀지 않는다. 날 무게로 내려가게 두고 후강·H형강은 속도를 낮춘다."),
            refStep(
              5,
              "전선관 나사는 다이스에 절삭유를 치고 1/4바퀴 되돌리며 낸다. 나사 길이 = 커플링 길이의 절반 + 1~2산.",
            ),
            refStep(6, "자른 뒤 리머로 안쪽 버를 깎는다. 남은 잔재는 규격을 적어 잔재 목록에 올린다."),
            refGap(),
            refSectionTitle("주의 사항"),
            refDataRow("숫돌", "고속절단기 숫돌에 금·이 빠짐이 있으면 쓰지 않는다. 숫돌 최고 회전수가 기계보다 높은지 본다. 덮개를 떼지 않는다."),
            refGap(),
            refDataRow("불꽃", "불꽃 방향에 배관·케이블·유류가 없게. 소화기 위치 확인."),
            refGap(),
            refDataRow("바이스", "자재를 바이스에 꽉 물린다. 짧은 조각을 손으로 잡고 자르지 않는다."),
            refGap(),
            refDataRow("밴드쏘", "날 장력·가이드를 맞춘 뒤 켠다. 날이 도는 동안 자재를 손으로 밀지 않는다."),
            refGap(),
            refSectionTitle("정비 (점검)"),
            refDataRow("숫돌", "닳아 작아지면 바꾼다. 습기에 두지 않는다."),
            refGap(),
            refDataRow("밴드쏘", "날 장력, 날 가이드, 절삭유 양을 본다. 날 이가 빠지면 바꾼다."),
            refGap(),
            refDataRow("공통", "바이스 나사에 쇳가루를 털고, 전원선·스위치를 본다. 카본 브러시는 서비스센터."),
            refGap(),
            refDataRow("나사 다이스", "날 이를 보고, 칩을 턴다."),
            refGap(),
            refSectionTitle("고장 났을 때"),
            refDataRow("비스듬히 잘린다", "바이스 각도, 밴드쏘 날 가이드·장력."),
            refGap(),
            refDataRow("밴드쏘 날이 자주 끊긴다", "장력이 너무 세다, 너무 빨리 내렸다, 날 이 수가 재질과 안 맞다."),
            refGap(),
            refDataRow("숫돌이 떨린다", "바로 멈춘다. 고정 너트·숫돌 금을 본다. 금이면 버린다."),
            refGap(),
            refDataRow("나사가 뜯긴다", "절삭유 부족, 다이스 날이 무디다."),
            refGap(),
            refSectionTitle("쓴 뒤 정리"),
            refStep(1, "전원을 끄고 플러그를 뽑는다."),
            refStep(2, "쇳가루·불꽃 찌꺼기를 치운다(불씨가 남는다)."),
            refStep(3, "밴드쏘를 오래 안 쓸 때는 날 장력을 풀어 둔다."),
            refStep(4, "숫돌은 마른 곳에 둔다. 남은 잔재는 규격을 적어 잔재 목록에 올린다."),
          ],
        ),
        const SizedBox(height: 16),

        refCard(
          title: "10. 멀티미터·HART 통신기로 4-20mA 루프 확인",
          subtitle: "전송기는 표시창에 압력, 루프 전류는 멀티미터로",
          icon: Icons.electrical_services,
          iconColor: Colors.deepOrange.shade600,
          children: [
            refSectionTitle("쓰는 순서"),
            refStep(
              1,
              "멀티미터를 DC mA 모드로 두고, 루프 +선 한 군데를 끊어 그 사이에 직렬로 문다. 두 선에 나란히(병렬) 대면 전압을 재게 되어 의미가 없다.",
            ),
            refStep(
              2,
              "판넬에 시험 단자대(test terminal block)가 있으면 선을 끊지 않고 클립만 꽂는다.",
            ),
            refStep(
              3,
              "HART 통신기가 있으면 루프를 끊지 않고도 통신기가 지금 mA·압력을 바로 읽어 온다. 선을 끊어야 하는 멀티미터는 그게 없을 때 쓴다.",
            ),
            refStep(
              4,
              "전송기 표시창은 그대로 공정값(압력)을 보여준다. 시험 압력을 올리면서 멀티미터 mA가 그 압력에 맞는 값(예: 0~10bar → 4~20mA)으로 따라오는지 본다.",
            ),
            refStep(
              5,
              "확인이 끝나면 끊었던 선을 원래대로 물리고, DCS·지시계에 통신·경보가 정상으로 돌아왔는지 본다.",
            ),
            refGap(),
            refWarnBox(
              "살아있는 제어 루프는 끊는 순간 신호가 튀거나 경보가 뜰 수 있다. 필요하면 제어실에 미리 알리거나 그 루프를 bypass 해 두고 한다.",
            ),
            refGap(),
            refTipBox(
              "전원·전선·HART 저항이 충분한지는 '계기 교정 → 루프 전압' 탭에서 미리 계산해 볼 수 있다. mA·오차를 점별로 기록하려면 '계기 교정 → 교정 점검' 탭을 쓴다.",
            ),
            refGap(),
            refSectionTitle("주의 사항"),
            refDataRow("단자", "mA 단자에 꽂은 채로 전압을 재지 않는다. 퓨즈가 나가거나 단락된다."),
            refGap(),
            refDataRow("계기 등급", "측정 범주(CAT)가 맞는 계기를 쓴다. 방폭 구역에서는 방폭 인증 계기만."),
            refGap(),
            refDataRow("살아있는 루프", "끊기 전에 제어실에 알리거나 bypass 한다(위 경고)."),
            refGap(),
            refSectionTitle("정비 (점검)"),
            refDataRow("배터리·퓨즈", "배터리와 mA 퓨즈를 본다. 퓨즈가 나가면 mA가 0으로 나온다."),
            refGap(),
            refDataRow("리드선", "피복이 벗겨지거나 끝이 헐거우면 바꾼다."),
            refGap(),
            refDataRow("교정 기한", "멀티미터·HART 통신기도 교정 기한이 있다. 장비 관리 대장에 올려 둔다."),
            refGap(),
            refSectionTitle("고장 났을 때"),
            refDataRow("mA가 0이다", "퓨즈가 나갔다, 리드선을 mA 단자에 안 꽂았다, 루프가 끊겼다."),
            refGap(),
            refDataRow("값이 튄다", "클립 접촉이 나쁘다. 다시 문다."),
            refGap(),
            refDataRow("값이 마이너스다", "극성이 반대다."),
            refGap(),
            refDataRow("HART가 응답하지 않는다", "루프에 250 Ω쯤의 저항이 있어야 통신된다. 전원·저항·주소를 본다."),
            refGap(),
            refSectionTitle("쓴 뒤 정리"),
            refStep(1, "리드선을 전압 단자로 돌려 꽂고 계기를 끈다."),
            refStep(2, "끊었던 선을 원래대로 물리고 조임을 확인한다."),
            refStep(3, "제어실에 끝났다고 알리고 bypass를 푼다."),
            refStep(4, "잰 값은 계기 교정 화면에 기록한다."),
          ],
        ),
        const SizedBox(height: 16),

        refCard(
          title: "11. GD402 가스 밀도계(요꼬가와) 보정",
          subtitle: "수소 순도 모니터. 화면 코드(영문)를 보고 YES·NO로 고르는 방식",
          icon: Icons.speed,
          iconColor: Colors.indigo,
          children: [
            refDataRow("제로가스", "수소(H2) 100%"),
            refGap(),
            refDataRow("스팬가스", "이산화탄소(CO2) 100%"),
            refGap(),
            refWarnBox(
              "수소순도계는 반자동·자동이 없고 수동 보정만 있다. 밀도계·열량계와 순서가 다르다 — "
              "아래 '전체 매뉴얼 보기'의 10장을 본다.",
            ),
            refGap(),
            refSectionTitle("주의 사항"),
            refDataRow("수소", "수소는 공기 중 4~75%에서 터진다. 불꽃·화기 금지, 정전기 주의."),
            refGap(),
            refDataRow("가스 용기", "보정 가스 용기를 넘어지지 않게 묶는다. 배기는 안전한 곳으로."),
            refGap(),
            refDataRow("샘플 라인", "보정 중 샘플 쪽 밸브 위치를 바꾸기 전에 운전원과 맞춘다."),
            refGap(),
            refSectionTitle("정비 (점검)"),
            refDataRow("정기 보정", "정해진 주기로 보정하고 결과를 적는다."),
            refGap(),
            refDataRow("샘플 계통", "필터 막힘·유량을 본다. 자세한 점검은 전체 매뉴얼 11장."),
            refGap(),
            refSectionTitle("고장 났을 때"),
            refDataRow("경보(ALM)·고장(Err)", "화면의 코드를 적고 아래 전체 매뉴얼의 경보표(11장)를 본다."),
            refGap(),
            refDataRow("보정이 안 맞는다", "가스 종류(제로 H2 100%·스팬 CO2 100%)와 유량, 보정 방식(수동)을 다시 본다."),
            refGap(),
            refSectionTitle("쓴 뒤 정리"),
            refStep(1, "밸브를 운전 위치로 되돌린다."),
            refStep(2, "보정 가스 용기 밸브를 잠근다."),
            refStep(3, "보정 값과 날짜를 기록한다(계기 교정·장비 대장)."),
            const SizedBox(height: 12),
            _openManualButton(context),
          ],
        ),
        const SizedBox(height: 16),

        refCard(
          title: "12. REMS 아미고 2 (전동 나사 절삭기)",
          subtitle: "손에 들고 쓰는 전동 다이스. 바이스 없이 받침대로 관에 물려 나사를 낸다",
          icon: LucideIcons.wrench,
          iconColor: Colors.red.shade700,
          children: [
            refSectionTitle("제원"),
            refDataRow("전동기", "1700 W"),
            refGap(),
            refDataRow("나사 내는 회전", "30~18 rpm"),
            refGap(),
            refDataRow("무게", "본체 6.5 kg (다이 헤드 빼고)"),
            refGap(),
            refDataRow("나사 범위", "관용 1/8~2\" (16~50 mm), 볼트 6~30 mm (1/4~1\"). 4\" 자동 다이 헤드를 달면 2 1/2~4\""),
            refGap(),
            refDataRow("구성", "본체, 크기별 다이 헤드, 받침대(서포트 브래킷), 공구함"),
            refGap(),
            refSectionTitle("주의 사항"),
            refDataRow("전원", "명판 전압 확인. 접지된 콘센트, 젖은 곳은 누전차단기 달린 전원. 연장선은 굵은 것, 감긴 채로 쓰지 않는다(뜨거워진다)."),
            refGap(),
            refDataRow("받침대", "받침대 없이 손으로만 잡고 켜지 않는다. 본체가 돌아가며 손목을 친다. 관이 흔들리면 관부터 고정한다."),
            refGap(),
            refDataRow("회전부", "도는 다이 헤드에 장갑·소매·수건이 닿지 않게. 보안경을 쓴다."),
            refGap(),
            refDataRow("방향 바꾸기", "완전히 멈춘 뒤에 방향을 바꾼다. 도는 중에 바꾸면 기어가 상한다."),
            refGap(),
            refDataRow("칩", "나사 칩은 날카롭다. 맨손으로 치우지 말고 솔로 턴다."),
            refGap(),
            refDataRow("절삭유", "넉넉히 친다. 먹는 물 관은 먹는 물용 절삭유. 바닥에 흘린 기름은 바로 닦는다(미끄럼)."),
            refGap(),
            refSectionTitle("쓰는 순서"),
            refStep(1, "관 끝을 직각으로 자르고 안쪽 버를 깎는다."),
            refStep(2, "관 크기 다이 헤드를 본체에 끝까지 끼운다."),
            refStep(3, "받침대를 관에 물리고, 다이 헤드를 관 끝에 직각으로 댄다."),
            refStep(4, "절삭유를 치며 나사를 낸다. 관 끝이 다이 헤드 앞면에 오면 멈춘다(규격 길이)."),
            refStep(5, "멈춘 뒤 방향을 바꿔 다이 헤드를 빼낸다."),
            refGap(),
            refSectionTitle("정비 (점검)"),
            refDataRow("쓸 때마다", "다이 헤드 칩·기름때를 솔로 털고, 날(체이서) 이가 깨졌는지 본다."),
            refGap(),
            refDataRow("날 바꾸기", "무디거나 깨진 날은 한 세트를 같이 바꾼다. 하나만 바꾸면 나사가 비뚤어진다."),
            refGap(),
            refDataRow("본체", "통풍구 먼지를 바람으로 불어 낸다. 전원선 피복·플러그 핀을 본다."),
            refGap(),
            refDataRow("카본 브러시·기어", "불꽃이 많아지거나 힘이 빠지면 카본 브러시가 닳은 것이다. 카본·기어는 직접 열지 말고 서비스센터에 맡긴다."),
            refGap(),
            refSectionTitle("고장 났을 때"),
            refDataRow("안 켜진다", "전원·차단기·연장선 → 플러그·스위치 → 그래도 안 되면 카본 브러시 의심, 서비스센터."),
            refGap(),
            refDataRow("나사가 뜯긴다", "절삭유 부족, 날이 무딤, 관 끝이 비스듬함. 스테인리스는 전용 날을 쓴다."),
            refGap(),
            refDataRow("나사가 비뚤다", "처음 댈 때 직각이 아니었다. 받침대 자리를 다시 잡고, 날 세트를 확인한다."),
            refGap(),
            refDataRow("힘이 약하다·멈춘다", "연장선이 가늘고 길다(전압이 떨어진다), 날이 무디다, 카본 브러시가 닳았다."),
            refGap(),
            refDataRow("본체가 뜨겁다", "오래 연달아 썼다. 잠깐 쉬어 식히고, 통풍구가 막혔는지 본다."),
            refGap(),
            refDataRow("타는 냄새·큰 불꽃", "바로 끄고 플러그를 뽑는다. 다시 쓰지 말고 서비스센터. 장비 대장에서 '수리·점검 중'으로 바꾼다."),
            refGap(),
            refDataRow("다이 헤드가 안 들어간다·안 빠진다", "자리에 칩이 끼었다. 플러그를 뽑고 청소한다."),
            refGap(),
            refSectionTitle("쓴 뒤 정리"),
            refStep(1, "플러그를 뽑는다."),
            refStep(2, "다이 헤드를 빼서 칩과 기름을 닦고, 녹 안 나게 기름을 얇게 바른다."),
            refStep(3, "본체의 기름·물기를 닦는다. 전원선은 꺾이지 않게 느슨히 감는다."),
            refStep(4, "다이 헤드는 크기별 자리에, 받침대와 같이 공구함에 넣는다. 절삭유 통을 닫는다."),
            refStep(5, "바닥의 칩·기름을 치운다. 장비 대장에서 반납하고, 이상이 있었으면 적어 둔다."),
            refGap(),
            refTipBox("이 카드는 현장에서 흔히 쓰는 요령입니다. 정비 주기·부품 번호는 아래 제조사 설명서가 먼저입니다."),
            const SizedBox(height: 12),
            _vendorManualButton(context, key: 'REMS|Amigo 2', title: 'REMS 아미고 2'),
          ],
        ),
        const SizedBox(height: 16),

        refCard(
          title: "13. REMS 타이거 SR (컷쏘)",
          subtitle: "파이프용 컷쏘(날이 앞뒤로 오가는 톱). 가이드 홀더를 관에 대면 바이스 없이 직각으로 자른다",
          icon: LucideIcons.scissors,
          iconColor: Colors.red.shade700,
          children: [
            refSectionTitle("제원"),
            refDataRow("전동기", "1400 W (230 V 6.4 A / 110 V 12.8 A)"),
            refGap(),
            refDataRow("무게", "3.0 kg"),
            refGap(),
            refDataRow("행정 속도", "SR은 전자식으로 속도를 조절한다(타이거 기본형은 고정)"),
            refGap(),
            refDataRow("가이드 홀더", "2\" 홀더 1/8~2\", 4\" 홀더 2 1/2~4\", 6\" 홀더 5~6\""),
            refGap(),
            refDataRow("쓰임", "강관·스테인리스·주철·플라스틱 관 절단, 홀더 없이 손으로 하는 절단"),
            refGap(),
            refSectionTitle("주의 사항"),
            refDataRow("자를 관", "안에 압력·가스·물이 남았는지 먼저 확인한다. 격리·배수·퍼지가 끝난 관만 자른다."),
            refGap(),
            refDataRow("날 뒤쪽", "날 끝이 관을 지나 뒤에 있는 배관·케이블·벽에 닿지 않는지 본다. 날 길이를 맞게 고른다."),
            refGap(),
            refDataRow("잘린 쪽", "잘리는 쪽 관이 떨어지지 않게 받치거나 묶는다. 무게에 날이 끼면 튄다."),
            refGap(),
            refDataRow("날 바꾸기", "반드시 플러그를 뽑고 바꾼다. 끼운 뒤 당겨서 잠겼는지 본다. 막 쓴 날은 뜨겁다."),
            refGap(),
            refDataRow("보호구", "보안경, 귀마개, 장갑. 스테인리스 쇳가루가 눈에 튄다."),
            refGap(),
            refSectionTitle("쓰는 순서"),
            refStep(1, "관 재질에 맞는 날을 고른다(강관·스테인리스는 고운 날, 플라스틱·나무는 굵은 날)."),
            refStep(2, "관 크기 가이드 홀더를 달고, 홀더를 관에 대어 절단선에 맞춘다."),
            refStep(3, "날이 관에 닿지 않게 두고 켠다. 천천히 내리고, SR은 들어가면 속도를 올린다."),
            refStep(4, "세게 누르지 않는다. 홀더가 힘을 받아 준다."),
            refStep(5, "다 자르면 끄고 날이 멈춘 뒤 뺀다. 자른 면 버를 깎는다."),
            refGap(),
            refSectionTitle("정비 (점검)"),
            refDataRow("쓸 때마다", "날 고정부(클램프)의 쇳가루를 턴다. 휘거나 이 빠진 날은 버린다."),
            refGap(),
            refDataRow("가이드 홀더", "고정 볼트가 풀리지 않았는지, 관에 닿는 면이 망가지지 않았는지 본다."),
            refGap(),
            refDataRow("본체", "통풍구 먼지를 불어 낸다. 전원선 피복·플러그 핀을 본다."),
            refGap(),
            refDataRow("카본 브러시·속 부품", "불꽃이 많거나 힘이 빠지면 카본 브러시가 닳은 것이다. 직접 열지 말고 서비스센터."),
            refGap(),
            refSectionTitle("고장 났을 때"),
            refDataRow("안 켜진다", "전원·차단기·연장선 → 플러그·스위치 → SR 속도 조절이 가장 낮게 되어 있지 않은지 → 서비스센터."),
            refGap(),
            refDataRow("날이 자꾸 빠진다", "클램프에 쇳가루가 끼었거나 날을 끝까지 안 끼웠다. 청소하고 다시 끼운다."),
            refGap(),
            refDataRow("날이 휜다·부러진다", "너무 세게 눌렀다, 날 종류가 안 맞다, 홀더 없이 비스듬히 잘랐다."),
            refGap(),
            refDataRow("잘린 면이 비뚤다", "홀더를 관에 붙이지 않았거나 날이 휘었다."),
            refGap(),
            refDataRow("잘 안 잘린다", "날이 무디다, 이가 재질에 안 맞다, 속도가 너무 빠르거나 느리다."),
            refGap(),
            refDataRow("떨림·소리가 크다", "날 고정·홀더 볼트가 풀렸다. 조여도 그대로면 속 부품 문제, 서비스센터."),
            refGap(),
            refDataRow("타는 냄새·큰 불꽃", "바로 끄고 플러그를 뽑는다. 장비 대장에서 '수리·점검 중'으로 바꾼다."),
            refGap(),
            refSectionTitle("쓴 뒤 정리"),
            refStep(1, "플러그를 뽑는다."),
            refStep(2, "날을 빼서 따로 보관한다(끼운 채로 케이스에 넣지 않는다). 쓴 날·새 날을 나눠 둔다."),
            refStep(3, "쇳가루를 털고 본체를 닦는다. 가이드 홀더도 닦아 같이 넣는다."),
            refStep(4, "전원선은 꺾이지 않게 느슨히 감아 케이스에 넣는다."),
            refStep(5, "자른 자리 쇳가루·잘라낸 관을 치운다. 장비 대장에서 반납하고, 이상이 있었으면 적어 둔다."),
            refGap(),
            refTipBox("톱날 두께(절단 손실)를 재서 튜브 컷팅·형강 컷팅 화면에 넣어 두면 재단 길이가 맞는다. 정비 주기·부품 번호는 제조사 설명서가 먼저입니다."),
            const SizedBox(height: 12),
            _vendorManualButton(context, key: 'REMS|Tiger SR', title: 'REMS 타이거 SR'),
          ],
        ),
        const SizedBox(height: 16),

        refCard(
          title: "14. 안전",
          subtitle: "매일 지키는 것",
          icon: LucideIcons.hardHat,
          iconColor: Colors.amber.shade800,
          children: [
            refDataRow(
              "보호구",
              "보안경(절단·연마 필수), 귀마개, 절단 장갑. 회전 장비 앞에서 면장갑은 말려 들어간다.",
            ),
            refGap(),
            refDataRow("유압", "호스·커플러 누유 확인. 램·슈 사이에 손 금지. 핀은 끝까지."),
            refGap(),
            refDataRow("전동 벤더", "비상 정지 자리를 먼저 확인. 암이 도는 반경 안에 사람·자재 없게."),
            refGap(),
            refDataRow(
              "무게",
              "6m 후강 54는 본당 약 36kg, H형강은 더 무겁다. 형강 탭의 무게로 미리 인원을 정한다.",
            ),
            refGap(),
            refDataRow("불꽃", "절단기 불꽃 방향에 배관·케이블·유류 없게. 소화기 위치 확인."),
            refGap(),
            refDataRow(
              "통신 없는 현장",
              "발전소 안에서는 앱이 폰에 저장했다가 통신되면 올린다. 저장 안 됐다고 다시 누르지 말고 나와서 확인.",
            ),
          ],
        ),
        const SizedBox(height: 40),
      ],
    );
  }
}
